# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 75acf08d73fa0136615a8c78916d44abf58dedab328f82e83bcf2760e3757b2e71205bc5d8e39d0c2c59fc1e4566fb79179123103ee17c009f6722fc2e4348ee

test:
  secret_key_base: 0bfc1a8dcd7013aba06df3306f3d48fb0560810b98e98eadc2b0de40e6bad2b4ece30a8028a5862bc8cd4474af437c7fd330eee464a53ec31d072eecf6ffb25b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
